[book]
authors = ["monoidog, mikelovic"]
language = "en"
multilingual = false
src = "src"
title = "FLOSH ASSEMBLY"

[build]
build-dir = "public"

[output.html]
cname="flosh.0x01.win"
smart-punctuation = false
git-repository-url = "https://github.com/jcmariscal/flosh-assembly-website"
edit-url-template = "https://github.com/jcmariscal/flosh-assembly-website/edit/main/{path}"
preferred-dark-theme = "navy"
default-theme = "navy"
